version: "2.4"
services:
  tailscale:
    hostname: aither                         # This will become the tailscale device name
    image: tailscale/tailscale:stable
    volumes:
      - "./tailscale_var_lib:/var/lib"       # State data will be stored in this directory
      - "/dev/net/tun:/dev/net/tun"          # Required for tailscale to work
    cap_add:                                 # Required for tailscale to work
      - net_admin
      - sys_module
    privileged: true
    env_file:
      - tailscale.env
    ports:
      - 6080:6080
      - 6081:6081
      - 6082:6082
      - 6083:6083
      - 6084:6085
      - 6086:6086
      - 6087:6087
      - 6088:6088
      - 6089:6089
      - 6090:6090
      - 8080:8080
    command: tailscaled

  aither:
    image: enokiinc/aither
#    build: .
    container_name: aither-baseimage
    privileged: true #optional
    environment:
      - XDG_RUNTIME_DIR=/home/dev
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY 
      - WLR_BACKENDS=headless
      - WLR_LIBINPUT_NO_DEVICES=1 
      - --user= dev
    command: dbus-run-session -- sway
    user: dev
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #optional
      - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/home/1000/$WAYLAND_DISPLAY
#    ports:
#      - 6080:6080
#      - 6081:6081
#      - 6082:6082
#      - 6083:6083
#      - 6084:6085
#      - 6086:6086
#      - 6087:6087
#      - 6088:6088
#      - 6089:6089
#      - 6090:6090
    network_mode: service:tailscale
    #shm_size: "1gb" #optional
    #restart: unless-stopped
